### ISSUE TITLE
[Bug]: Tag component on mobile, enter not adding new tag

### ISSUE THREAD

**Issue by tjhunkin** [robsontenorio/mary#277] opened 2024-01-25 15:47 UTC
### MaryUI version

latest

### daisyUI version

latest

### Livewire version

latest

### What browsers are affected?

Chrome

### What happened?

typing in a new value on mobile (android) in a tag component, you can't press enter to add the new tag, it goes to the next element. Then the value typed in clears straight after.

**Comment by robsontenorio** [comment] 2024-01-25 16:29
I can’t reproduce on iPhone. 

Could please attach a video ?

**Comment by tjhunkin** [comment] 2024-01-25 17:26
I'm using Android

**Comment by tjhunkin** [comment] 2024-01-25 17:33
https://recorder.page.link/Best

**Comment by tjhunkin** [comment] 2024-01-25 17:38
https://drive.google.com/file/d/16Mpy5221FuKGer-_B4xwXBJOKwRd1Cj1/view?usp=drivesdk

**Comment by robsontenorio** [comment] 2024-01-25 20:00
I am not android user. But it seems the “Next” button is acting as “Tab” on desktop. 

I will try to setup a simulator.

**Comment by tjhunkin** [comment] 2024-01-25 20:09
Thank you

**Comment by IamSAB** [comment] 2024-02-06 23:03
Same here on Android with Firefox.
Keyboard shows no enter, but only a tab.

That way you are unable to add any tags.

In adition, the cursor is not centered but at the bottom of the form which is also heigher.

![Screenshot_20240207-000245_Firefox](https://github.com/robsontenorio/mary/assets/8931240/2ad2b8f7-79c3-4a90-bc1b-0905778e2278)

**Comment by robsontenorio** [comment] 2024-02-09 12:21
The issue here it is because on Android the primary button action is a “Next” , so it is equivalent to a “tab”. 

On iOS the primary button action is a “Go” , so it is equivalent to a “enter” and it works as same on desktop. 

Probably I should add “tab” as a trigger as well.

**Comment by truthytech** [comment] 2024-02-09 12:29
Yes please, this is currently extremely cumbersome as I need to create a separate lookup field that populates the tag field and I need to switch to desktop in order to capture any new tags, it's a real pain to say the least.

**Comment by robsontenorio** [comment] 2024-02-16 15:00
@truthytech @IamSAB @tjhunkin 

It will be fixed on next release.

**Closed by robsontenorio** 2024-02-16 15:00 UTC
Labels: enhancement

**Comment by tjhunkin-inhance** [comment] 2024-02-16 15:05
Thank you

**Comment by tjhunkin-inhance** [comment] 2024-03-01 07:23
I updated to the latest version but still can't seem to capture a new entry on android

**Comment by robsontenorio** [comment] 2024-03-01 12:08
@tjhunkin 

Have you make sure your composer.json is updated to latest version ? Maybe a hard refresh o mobile browser ?

@IamSAB @truthytech 

Do you confirm ?

**Comment by robsontenorio** [comment] 2024-03-01 16:36
@tjhunkin Fixed on latest 1.25.2 release.
