### ISSUE TITLE
x-choices and wire:model.live issue

### ISSUE THREAD

**Issue by bucari** [robsontenorio/mary#188] opened 2023-12-06 15:50 UTC
### MaryUI version

1.7.0

### daisyUI version

4.4.19

### Livewire version

3.2.6

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

I don't know if it's a bug but using wire:model.live, when i type something to search, the property set in wire:model.live contains what i typed and then the search function goes in error 

```
    public function searchUtente(string $value = '')
    {
        $selectedOption = array();
        if (is_numeric($this->user_id)) // added this to prevent sql error
            $selectedOption = User::where('id', $this->user_id)->get(); //  $this->user_id contains the same value of $value parameter

        $this->utenti = User::query()
            ->where('name', 'ilike', "%$value%")
            ->take(20)
            ->orderBy('cognome')
            ->get()
            ->merge($selectedOption);
    }
```

**Comment by robsontenorio** [comment] 2023-12-06 16:37
@bucari 

Actually is not a bug, but a missing feature. 
Right now I don’t know if a can add this due to internal limitations.

**Comment by robsontenorio** [comment] 2023-12-07 14:49
@bucari 

Could you try this branch?

```sh
composer require robsontenorio/mary:dev-choices-live

php artisan view:clear
```

**Comment by robsontenorio** [comment] 2023-12-07 23:59
Fixed on latest release.

**Closed** 2023-12-08 00:00 UTC
Labels: enhancement
