### ISSUE TITLE
Using an array as the options for a Choices component breaks when user searches

### ISSUE THREAD

**Issue by hamannjames** [robsontenorio/mary#301] opened 2024-02-14 23:15 UTC
### MaryUI version

1.20.1

### daisyUI version

4.7.1

### Livewire version

3.4.4

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

When using an array or standard collection for the options in a Choices component, the component will render options as an object when the options are filtered via a search function. This is due to how json_encode works in PHP. It will render non-sequential arrays as an object, and you get a non-sequential array back when you filter. When this happens the "seletedOption" function client-side breaks, because it expects an array to call .filter on. Here are screenshots of the error and of the rendered options.

Error: 

<img width="587" alt="Screenshot 2024-02-14 at 3 12 20 PM" src="https://github.com/robsontenorio/mary/assets/18225435/b0e7c626-b536-48f9-a626-5dd4c743b7c9">

Before search (note the opening array bracket):

<img width="448" alt="Screenshot 2024-02-14 at 3 12 39 PM" src="https://github.com/robsontenorio/mary/assets/18225435/e99de6f4-0e9f-4837-8371-4cabecfc02da">

After search (note the opening object bracket):

<img width="365" alt="Screenshot 2024-02-14 at 3 12 51 PM" src="https://github.com/robsontenorio/mary/assets/18225435/2a874a86-90b7-48d5-ac0e-0e018b1d0725">

When the user types in enough to filter to one item, it works again.

This can be mitigated by calling array_values on the filtered array before assigning it to the property that options uses. This provides a sequential array which makes json_encode return an array instead of an object.

**Comment by robsontenorio** [comment] 2024-02-14 23:56
Please , share the relevant code from your app with markdown formatting.

**Comment by hamannjames** [comment] 2024-02-15 01:39
Certainly:

Say we use the component like this:

```
<x-choices 
    wire:model.live="model"
    :options="$models"
    :option-label="$optionLabel"
    :option-sub-label="$optionSubLabel"
    :$single
    searchable
    :$label
    :$icon
/>
```

And this is the relevant my server-side component:

```
public string $modelClass;
public Collection | Array $models;
public Collection | Array $items;

public function mount() {
    $this->search();
}

public function search($input = '')
{
    if ($this->modelClass) {
        // this works. It returns an eloquent collection
        $this->models = $this->modelClass::where($this->searchProp, 'like', '%'.$input.'%')->get();
    } else {
        // this does not. It returns a standard collection that does not have sequential keys
        $this->models = collect($this->items)->filter(function ($model) use ($input) {
            return str_contains(strtolower($model[$this->optionLabel]), strtolower($input));
        });
    }
}
```

The above code will work if I do this:

```
$this->models = array_values(collect($this->items)->filter(function ($model) use ($input) {
    return str_contains(strtolower($model[$this->optionLabel]), strtolower($input));
})->toArray());
```

**Comment by robsontenorio** [comment] 2024-02-15 03:07
A few things :

- Use “wire:model” , not “live”. The search function itself will trigger the component refreshing. 

- It is a bit weird you are mixing two different “sources” of items. It probably will break if the “structure” of items are different from each sorice . It was design to work with one kind of “source of truth”

- The choices components works with array and collections. But , you need to declare what’s the “key”. By default it is “id” key, but you can set anything. Check the custom attributes docs for choices. 

Try to simplify the things for now and check what is the root issue.

**Comment by hamannjames** [comment] 2024-02-15 04:13
To address your feedback:

I've found I need to use .live to make certain functionality like Reactive props to child components work. Regardless, I don't think it has anything to do with this problem.

You have to use two sources of truths if you are using an array as the source of truth. This is because you need to assign a new value to the property and that value will be a filtered list. If you are using an eloquent collection of models this is fine because every new search you can do a DB query. But if you are using an array you override the original list, and eventually run out of options. Also I know this has nothing to do with the problem.

The array I am using contains an array of arrays with a key of id. So it is saving the values appropriately. 

Regardless of that, I think I am at the root of the problem or at least close. I fixed it when passing in a sequential array, and the component is working as expected otherwise. Also none of the documentation mentions how to work with an array instead of a Collection, I just assumed it could work on it because of the type expected in the source code. But with the problems I've encountered, it doesn't seem like that is supposed to happen, or at least that feature hasn't been fully tested yet.

**Comment by hamannjames** [comment] 2024-02-16 00:14
Have you had a chance to look at my feedback? I know I can't be the only one encountering this issue when trying to use an array instead of a collection. I am assuming you have tested using arrays as the source of truth. If you have and cannot replicate the issue, maybe the documentation can be updated to better show how to use arrays as the source of truth for a choices component.

**Comment by robsontenorio** [comment] 2024-02-16 00:45
If you take exactly example from docs , and convert the result search to array it will work. No matter where you fetch or how you filter the data, but you should stick with array or collection, not both. 

The issue is because you have a condicional that sometimes return an array and sometimes a collection.

**Comment by hamannjames** [comment] 2024-02-16 00:57
The conditional is only there in case the component is set up to return eloquent collections or simple arrays. Depending on how the component is instantiated, it will return only one or the other during its lifecycle. It depends on whether it is looking for a specific model class in the DB, or using another dataset, like an array. 

I think it is clear I am using the this component in a way that is not intended. It looks like it is intended to query and filter database collections, and I am using it for either that, or to filter an array or collection already in memory, and this is where I am running into the issue.

**Comment by robsontenorio** [comment] 2024-02-16 01:30
Yes, the search function returning type must be an array or collection , not both. As well the property to hold those  items.  

I am closing this for now.

**Closed by robsontenorio** 2024-02-16 01:30 UTC
Labels: question
